name: CI/CD for API

on:
  push:
    branches: [master]
    paths:
      - "backend/**"
      - ".github/workflows/DeployApi.yaml"

jobs:
  deploy-api:
    name: Deploy API to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cat >~/.netrc <<"EOF
          machine api.heroku.com
          login meszarosdezsodev@gmail.com
          password ${{ secrets.HEROKU_TOKEN }}
          machine git.heroku.com
          login meszarosdezsodev@gmail.com
          password ${{ secrets.HEROKU_TOKEN }}
          EOF"
        working-directory: ./backend

      - uses: akhileshns/heroku-deploy@v3.0.5 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "meszarosdezso"
          heroku_email: "meszarosdezsodev@gmail.com"
          usedocker: false
          branch: "master"
