name: CI/CD

on:
  push:
    branches: [master]

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.ORG_ID}}
          now-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./client

  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy api"
        run: git push -f https://heroku:${{ secrets.HEROKU_TOKEN }}@git.heroku.com/meszarosdezso.git origin/master:master
        working-directory: ./api
