name: CI/CD

on:
  push:
    branches: [master]

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.ORG_ID}}
          now-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./client

  deploy-api:
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "meszarosdezso"
          heroku_email: "meszarosdezsodev@gmail.com"
          working-directory: ./api
